site_name: MadCAD Setup
site_description: Documentação de instalação e problemas do pymadcad/uimadcad
repo_url: https://github.com/dionarley/madcad

theme:
  name: material
  palette:
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: deep blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: true

nav:
  - Início: index.md
  - Instalação: installation.md
  - Problemas: problems.md
  - Exemplos: examples.md
  - Scripts: scripts.md
  - Docker: docker.md
